# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dmp/2.4.0 branch
on:
  push:
    branches: [ dmp/2.4.0 ]
  pull_request:
    branches: [ dmp/2.4.0 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Publish Gitbook
      uses: tuliren/publish-gitbook@v1.0.0
      with:
       # Github token for the repo
        github_token: $GITHUB_TOKEN
    - name: GitBook PDF
      run: gitbook pdf . DMP用户接入手册V2-4-0.pdf
